[unstable]
# build-std = ["core", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]

[build]
#target = "target.json"
rustflags = ["-C", "link-arg=-nostdlib", "-C", "link-arg=-static", "-C", "link-arg=-Wl,-T./shellcode.ld,--build-id=none", "-C", "relocation-model=pic"]
